[build]
    command = "npm run netlify"
    publish = "public"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/ama"
    to = "https://github.com/bradgarropy/ama#readme"
    status = 301

[[redirects]]
    from = "/dotfiles"
    to = "https://github.com/bradgarropy/dotfiles"
    status = 301

[[redirects]]
    from = "/netlify"
    to = "https://app.netlify.com"
    status = 301

[[redirects]]
    from = "/stream"
    to = "https://twitch.tv/bradgarropy"
    status = 301

[[redirects]]
    from = "/codetunes"
    to = "https://youtube.com/playlist?list=PL6Mu1AMmTL-vlrGehLTnA_MCjI4Bjx92r"
    status = 301

[[redirects]]
    from = "/discord"
    to = "https://discord.gg/WxtUPSF"
    status = 301

[[redirects]]
    from = "/donate"
    to = "https://paypal.me/bradgarropy"
    status = 301

[[redirects]]
    from = "/store"
    to = "https://cottonbureau.com/people/brad-garropy"
    status = 301

[[redirects]]
    from = "/sponsor"
    to = "https://github.com/sponsors/bradgarropy"
    status = 301

[[redirects]]
    from = "/podcast"
    to = "https://webdevweekly.captivate.fm"
    status = 301

[[redirects]]
    from = "/wdw"
    to = "https://webdevweekly.captivate.fm"
    status = 301

[[redirects]]
    from = "/webdevweekly"
    to = "https://webdevweekly.captivate.fm"
    status = 301

[[redirects]]
    from = "/subscribe"
    to = "https://www.getrevue.co/profile/bradgarropy"
    status = 301

[[redirects]]
    from = "/newsletter"
    to = "https://www.getrevue.co/profile/bradgarropy"
    status = 301
